// <auto-generated />
using System;
using KyudosudokuWebsite.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KyudosudokuWebsite.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20260325233616_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KyudosudokuWebsite.Database.Puzzle", b =>
                {
                    b.Property<int>("PuzzleID")
                        .HasColumnType("int");

                    b.Property<double?>("AverageTime")
                        .HasColumnType("float");

                    b.Property<string>("ConstraintNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Constraints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Generated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Invalid")
                        .HasColumnType("bit");

                    b.Property<string>("KyudokuGrids")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumConstraints")
                        .HasColumnType("int");

                    b.Property<int?>("TimeToGenerate")
                        .HasColumnType("int");

                    b.HasKey("PuzzleID");

                    b.ToTable("Puzzles");
                });

            modelBuilder.Entity("KyudosudokuWebsite.Database.Session", b =>
                {
                    b.Property<string>("SessionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SessionID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("KyudosudokuWebsite.Database.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("BackspaceOption")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PlayInvalidSound")
                        .HasColumnType("bit");

                    b.Property<bool>("SemitransparentXs")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowErrors")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowSolveTime")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KyudosudokuWebsite.Database.UserPuzzle", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("PuzzleID")
                        .HasColumnType("int");

                    b.Property<string>("Progess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SolveTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Solved")
                        .HasColumnType("bit");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("UserID", "PuzzleID");

                    b.ToTable("UserPuzzles");
                });
#pragma warning restore 612, 618
        }
    }
}
