//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KyudosudokuWebsite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KyudosudokuWebsite.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Css {
            get {
                object obj = ResourceManager.GetObject("Css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert(&apos;yes&apos;);.
        /// </summary>
        internal static string FindJs {
            get {
                return ResourceManager.GetString("FindJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window.addEventListener(&apos;DOMContentLoaded&apos;, function()
        ///{
        ///    let colors = [
        ///        [&quot;white&quot;, &quot;hsl(0, 0%, 50%)&quot;],
        ///        [&quot;hsl(0, 100%, 94%)&quot;, &quot;hsl(0, 70%, 50%)&quot;],
        ///        [&quot;white&quot;, &quot;hsl(0, 0%, 50%)&quot;],
        ///        [&quot;hsl(52, 100%, 89%)&quot;, &quot;hsl(52, 100%, 35%)&quot;],
        ///        [&quot;hsl(0, 0%, 94%)&quot;, &quot;hsl(0, 0%, 40%)&quot;],
        ///        [&quot;hsl(226, 100%, 94%)&quot;, &quot;hsl(226, 60%, 50%)&quot;],
        ///        [&quot;white&quot;, &quot;hsl(0, 0%, 50%)&quot;],
        ///        [&quot;hsl(103, 84%, 95%)&quot;, &quot;hsl(103, 50%, 50%)&quot;],
        ///        [&quot;white&quot;, &quot;hsl(0, 0%, 50%)&quot;]
        ///    ];
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PuzzleJs {
            get {
                return ResourceManager.GetString("PuzzleJs", resourceCulture);
            }
        }
    }
}
